import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Searchbar from "../components/Searchbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="bg-[#3d3939]">
          <Navbar />
          <Searchbar />
        </div>
      </div>
    </div>
  );
}
